apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: payment-service
          image: ghcr.io/YOUR_GITHUB_USERNAME/payment-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: KAFKA_BROKERS
              value: "kafka:9092"
            - name: KAFKA_CLIENT_ID
              value: "payment-service"
            - name: PAYMENT_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PAYMENT_DATABASE_URL
            - name: PAYMENT_SERVICE_PORT
              value: "3002"
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 40
            periodSeconds: 20